name: 'ZEIT Now Deployment'
description: 'This action make a deployment with github actions instead of ZEIT Now builder.'
inputs:
  zeit-token:
    description: 'zeit.co token'
    required: true
  zeit-team-id:
    description: ' This is required if your deployment is made on team project.'
    required: false
  now-args:
    description: ''
    required: false
    default: ''
  github-comment:
    required: false
    default: 'true'
    description: 'if you want to comment on pr and commit, set true, default: true'
  github-token:
    required: false
    description: 'if you want to comment on pr and commit, set token'
  github-deployment:
    required: false
    default: 'false'
    description: 'if you want to create github deployment, set true, default: false'
  working-directory:
    required: false
    description: the working directory

outputs:
  preview-url:
    description: 'deployment preview URL'

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'check'
  color: 'black'
