version: 2

jobs:
  build:
    docker:
      - image: node:12.16.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy-development:
    docker:
      - image: node:12.16.0
    steps:
      - checkout
      - run:
          name: Deploy Zeit Now - Development
          command: |
            npx now --token $ZEIT_API_TOKEN

workflows:
  version: 2
  build-deploy-development:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deploy-development:
          requires:
            - build
          filters:
            branches:
              only: develop
